#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nv.PriorityQueue
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QueueDemo")]
	public partial class QueueContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public QueueContext() : 
				base(global::nv.PriorityQueue.Properties.Settings.Default.QueueDemoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QueueContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QueueContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QueueContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QueueContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="jobs.usp_Dequeue")]
		public ISingleResult<usp_DequeueResult> Dequeue()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<usp_DequeueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="jobs.usp_Enqueue")]
		public void Enqueue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeId", DbType="TinyInt")] System.Nullable<byte> typeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Payload", DbType="VarChar(MAX)")] string payload, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenantId", DbType="SmallInt")] System.Nullable<short> tenantId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrincipalId", DbType="SmallInt")] System.Nullable<short> principalId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Priority", DbType="TinyInt")] System.Nullable<byte> priority)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), typeId, payload, tenantId, principalId, priority);
		}
	}
	
	public partial class usp_DequeueResult
	{
		
		private long _Id;
		
		private short _TenantId;
		
		private string _Payload;
		
		private byte _Priority;
		
		public usp_DequeueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL")]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenantId", DbType="SmallInt NOT NULL")]
		public short TenantId
		{
			get
			{
				return this._TenantId;
			}
			set
			{
				if ((this._TenantId != value))
				{
					this._TenantId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payload", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Payload
		{
			get
			{
				return this._Payload;
			}
			set
			{
				if ((this._Payload != value))
				{
					this._Payload = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="TinyInt NOT NULL")]
		public byte Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
